[versions]
#app
app-compileSdk = "36"
app-targetSdk = "36"
app-minSdk = "24"

#libs
androidDesugarJdkLibs = "2.1.5"
agp = "8.13.2"
gradle = "8.13.2"
kotlin = "2.2.21"
coreKtx = "1.17.0"
junit = "4.13.2"
junitVersion = "1.3.0"
espressoCore = "3.7.0"
lifecycleRuntimeKtx = "2.10.0"
lifecycleViewModelKmp = "2.9.6"
activityCompose = "1.12.1"
composeBom = "2025.12.00"
material3 = "1.4.0"
material3WindowSizeClass = "1.4.0"
ktor-client = "3.3.1"
kotlinxSerializationJson = "1.9.0"
coil = "2.7.0"
composeRuntime = "1.10.0"
lifecycleRuntimeCompose = "2.10.0"

#testing
junit5 = "6.0.1"
googleTruth = "1.4.5"

#plugin
googleServices = "4.4.4"
firebaseAppDistribution = "5.2.0"
ksp = "2.2.0-2.0.2"

jvmTarget = "21"
appcompat = "1.7.0"
material = "1.12.0"
org-jetbrains-kotlin-jvm = "2.2.21"
navigationRuntimeKtx = "2.9.6"
navigationCompose = "2.9.6"
foundationLayoutAndroid = "1.10.0"
foundationAndroid = "1.10.0"

room = "2.8.4"
roomCommon = "2.8.4"
roomKtx = "2.8.4"
navigationCommonKtx = "2.9.6"
datastoreVersion = "1.2.0"

#protobuf
protobufGradlePlugin = "0.9.5"
protobufJavalite = "4.33.2"
protobufKotlinLite = "4.33.2"
#protobuf

#region koin
koin = "4.1.1"
koinCompose = "4.1.1"
koin-ksp = "2.3.1"
appcompatVersion = "1.7.1"
materialVersion = "1.13.0"
#endregion koin

#region navigation3
nav3Core = "1.0.0"
lifecycleViewmodelNav3 = "2.10.0"
material3AdaptiveNav3 = "1.3.0-alpha05"
#endregion navigation3

[libraries]
android-desugarJdkLibs = { group = "com.android.tools", name = "desugar_jdk_libs", version.ref = "androidDesugarJdkLibs" }
androidx-core-ktx = { group = "androidx.core", name = "core-ktx", version.ref = "coreKtx" }
gradle = { module = "com.android.tools.build:gradle", version.ref = "gradle" }
junit = { group = "junit", name = "junit", version.ref = "junit" }
androidx-junit = { group = "androidx.test.ext", name = "junit", version.ref = "junitVersion" }
androidx-espresso-core = { group = "androidx.test.espresso", name = "espresso-core", version.ref = "espressoCore" }
androidx-lifecycle-runtime-ktx = { group = "androidx.lifecycle", name = "lifecycle-runtime-ktx", version.ref = "lifecycleRuntimeKtx" }
androidx-activity-compose = { group = "androidx.activity", name = "activity-compose", version.ref = "activityCompose" }
androidx-compose-bom = { group = "androidx.compose", name = "compose-bom", version.ref = "composeBom" }
androidx-ui = { group = "androidx.compose.ui", name = "ui" }
androidx-ui-graphics = { group = "androidx.compose.ui", name = "ui-graphics" }
androidx-ui-tooling = { group = "androidx.compose.ui", name = "ui-tooling" }
androidx-ui-tooling-preview = { group = "androidx.compose.ui", name = "ui-tooling-preview" }
androidx-ui-test-manifest = { group = "androidx.compose.ui", name = "ui-test-manifest" }
androidx-ui-test-junit4 = { group = "androidx.compose.ui", name = "ui-test-junit4" }
androidx-material3 = { group = "androidx.compose.material3", name = "material3", version.ref = "material3" }
androidx-lifecycle-viewmodel = { group = "org.jetbrains.androidx.lifecycle", name = "lifecycle-viewmodel", version.ref = "lifecycleViewModelKmp" }
# https://mvnrepository.com/artifact/androidx.compose.runtime/runtime
compose-runtime = { group = "androidx.compose.runtime", name = "runtime", version.ref = "composeRuntime" }
# https://mvnrepository.com/artifact/androidx.lifecycle/lifecycle-runtime-compose?repo=google
lifecycle-runtime-compose = { group = "androidx.lifecycle", name = "lifecycle-runtime-compose", version.ref = "lifecycleRuntimeCompose" }

kotlinx-serialization-json = { group = "org.jetbrains.kotlinx", name = "kotlinx-serialization-json", version.ref = "kotlinxSerializationJson" }

koin-core = { group = "io.insert-koin", name = "koin-core", version.ref = "koin" }
koin-android = { group = "io.insert-koin", name = "koin-android", version.ref = "koin" }
koin-android-compose = { group = "io.insert-koin", name = "koin-androidx-compose", version.ref = "koinCompose" }
koin-test = { group = "io.insert-koin", name = "koin-test", version.ref = "koin" }
koin-test-junit = { group = "io.insert-koin", name = "koin-test-junit4", version.ref = "koin" }
di-koin-ksp = { module = "io.insert-koin:koin-ksp-compiler", version.ref = "koin-ksp" }

coil = { group = "io.coil-kt", name = "coil-compose", version.ref = "coil" }

# Ktor
ktor-client-android = { group = "io.ktor", name = "ktor-client-android", version.ref = "ktor-client" }
ktor-client-negotiation = { group = "io.ktor", name = "ktor-client-content-negotiation", version.ref = "ktor-client" }
ktor-client-logging = { group = "io.ktor", name = "ktor-client-logging-jvm", version.ref = "ktor-client" }
ktor-client-serialization = { group = "io.ktor", name = "ktor-serialization-kotlinx-json", version.ref = "ktor-client" }
ktor-client-auth = { group = "io.ktor", name = "ktor-client-auth", version.ref = "ktor-client" }
# Ktor

# region adaptive
androidx-material3-adaptive-navigation-suite = { module = "androidx.compose.material3:material3-adaptive-navigation-suite" }
androidx-material3-window-sizeclass = { module = "androidx.compose.material3:material3-window-size-class", version.ref = "material3WindowSizeClass" }
androidx-adaptive = { module = "androidx.compose.material3.adaptive:adaptive" }
androidx-adaptive-layout = { module = "androidx.compose.material3.adaptive:adaptive-layout" }
androidx-adaptive-navigation = { module = "androidx.compose.material3.adaptive:adaptive-navigation" }
#endregion adaptive

#region Testing
# https://mvnrepository.com/search?q=org.junit.jupiter
test-junit-jupiter = { group = "org.junit.jupiter", name = "junit-jupiter", version.ref = "junit5" }
# https://mvnrepository.com/artifact/org.jetbrains.kotlin/kotlin-test-junit5
kotlin-test-junit5 = { module = "org.jetbrains.kotlin:kotlin-test-junit5", version.ref = "kotlin" }
# https://mvnrepository.com/artifact/com.google.truth/truth
truth = { module = "com.google.truth:truth", version.ref = "googleTruth" }
#endregion Testing

# Dependencies of the included build-logic
kotlin-gradlePlugin = { group = "org.jetbrains.kotlin", name = "kotlin-gradle-plugin", version.ref = "kotlin" }
androidx-navigation-runtime-ktx = { group = "androidx.navigation", name = "navigation-runtime-ktx", version.ref = "navigationRuntimeKtx" }
androidx-navigation-compose = { group = "androidx.navigation", name = "navigation-compose", version.ref = "navigationCompose" }
androidx-foundation-layout-android = { group = "androidx.compose.foundation", name = "foundation-layout-android", version.ref = "foundationLayoutAndroid" }
androidx-foundation-android = { group = "androidx.compose.foundation", name = "foundation-android", version.ref = "foundationAndroid" }

room-core = { group = "androidx.room", name = "room-runtime", version.ref = "room" }
room-compiler = { group = "androidx.room", name = "room-compiler", version.ref = "room" }
room-common = { group = "androidx.room", name = "room-common", version.ref = "roomCommon" }
room-ktx = { group = "androidx.room", name = "room-ktx", version.ref = "roomKtx" }
androidx-navigation-common-ktx = { group = "androidx.navigation", name = "navigation-common-ktx", version.ref = "navigationCommonKtx" }

# https://mvnrepository.com/artifact/androidx.datastore/datastore
datastore = { group = "androidx.datastore", name = "datastore", version.ref = "datastoreVersion" }
#region Protobuf
# https://mvnrepository.com/artifact/com.google.protobuf/protobuf-javalite
protobuf-javalite = { group = "com.google.protobuf", name = "protobuf-javalite", version.ref = "protobufJavalite" }
# https://mvnrepository.com/artifact/com.google.protobuf/protobuf-kotlin-lite
protobuf-kotlin-lite = { group = "com.google.protobuf", name = "protobuf-kotlin-lite", version.ref = "protobufKotlinLite" }
# https://mvnrepository.com/artifact/com.google.protobuf/protobuf-gradle-plugin
protobuf-gradle-plugin = { group = "com.google.protobuf", name = "protobuf-gradle-plugin", version.ref = "protobufGradlePlugin" }
androidx-appcompat = { group = "androidx.appcompat", name = "appcompat", version.ref = "appcompatVersion" }
material = { group = "com.google.android.material", name = "material", version.ref = "materialVersion" }
#endregion Protobuf

#region navigation3
androidx-navigation3-runtime = { module = "androidx.navigation3:navigation3-runtime", version.ref = "nav3Core" }
androidx-navigation3-ui = { module = "androidx.navigation3:navigation3-ui", version.ref = "nav3Core" }

# Optional add-on libraries
androidx-lifecycle-viewmodel-navigation3 = { module = "androidx.lifecycle:lifecycle-viewmodel-navigation3", version.ref = "lifecycleViewmodelNav3" }
androidx-material3-adaptive-navigation3 = { group = "androidx.compose.material3.adaptive", name = "adaptive-navigation3", version.ref = "material3AdaptiveNav3" }
#endregion navigation3

[bundles]
#implement compose-bom platform first
koin = ["koin.core", "koin.android", "koin.android.compose"]
ktor = ["ktor.client.android", "ktor.client.negotiation", "ktor.client.serialization", "ktor.client.logging", "ktor.client.auth"]

[plugins]
android-application = { id = "com.android.application", version.ref = "agp" }
kotlin-android = { id = "org.jetbrains.kotlin.android", version.ref = "kotlin" }
kotlin-compose = { id = "org.jetbrains.kotlin.plugin.compose", version.ref = "kotlin" }

android-app-module-conventions = { id = "com.oleksandr.android.application" }
android-koin-conventions = { id = "com.oleksandr.android.koin" }
android-test-conventions = { id = "com.oleksandr.android.test" }
kotlin-test-conventions = { id = "com.oleksandr.kotlin.test" }

android-library = { id = "com.android.library", version.ref = "agp" }
compose-compiler = { id = "org.jetbrains.kotlin.plugin.compose", version.ref = "kotlin" }
kotlin-serialization = { id = "org.jetbrains.kotlin.plugin.serialization", version.ref = "kotlin" }
google-services = { id = "com.google.gms.google-services", version.ref = "googleServices" }
firebase-appDistribution = { id = "com.google.firebase.appdistribution", version.ref = "firebaseAppDistribution" }
ksp = { id = "com.google.devtools.ksp", version.ref = "ksp" }
org-jetbrains-kotlin-jvm = { id = "org.jetbrains.kotlin.jvm", version.ref = "org-jetbrains-kotlin-jvm" }
#firebase-crashlytics = { id = "com.google.firebase.crashlytics", version.ref = "firebase-crashlytics" }

